## Set

1. Create a list called `sensor_readings = [22.5, 23.0, 22.5, 24.1, 23.0, 25.0]`.
2. Convert `sensor_readings` to a set named `unique_readings` to find all distinct temperature values. Print
`unique_readings` and its length.
3. Attempt to add `24.1` to `unique_readings` and then `26.0`. Print the set after each operation.

In [2]:
sensor_readings = [22.5, 23.0, 22.5, 24.1, 23.0, 25.0]
#print(sensor_readings)
unique_readings=set(sensor_readings)
print(unique_readings)

{24.1, 25.0, 22.5, 23.0}


In [3]:
type(unique_readings)

set

In [4]:
unique_readings.add(24.1)

In [5]:
unique_readings

{22.5, 23.0, 24.1, 25.0}

In [6]:
unique_readings.add(26.0)
unique_readings



{22.5, 23.0, 24.1, 25.0, 26.0}

1. You have a set of active users: `active_users = {"Alice", "Bob", "Charlie", "David"}`.
2. Remove "Charlie" from the set.
3. Use `pop()` to remove an arbitrary user and print the removed user's name and the updated set.
4. Try to remove "Eve" from the set using `remove()` (expect a `KeyError`). Then, use `discard()` to try and remove "Eve"
again and observe the difference.

In [7]:
active_users = {"Alice", "Bob", "Charlie", "David"}
active_users.remove("Charlie")

In [8]:
active_users

{'Alice', 'Bob', 'David'}

In [9]:
a=active_users.pop()
print(a)

David


In [10]:
active_users

{'Alice', 'Bob'}

In [11]:
active_users.remove("Eve")

KeyError: 'Eve'

In [12]:
try:
    active_users.remove("Eve")
except KeyError as e:
    print("KeyError is:",e)

KeyError is: 'Eve'


In [13]:
active_users.discard("Eve")
print(active_users)

{'Alice', 'Bob'}


1. You have two sets of programming languages: `frontend_langs = {"HTML", "CSS", "JavaScript", "Python"}` and
`backend_langs = {"Python", "Java", "C#", "SQL"}`.
2. Find all unique languages from both sets (union).
3. Find languages common to both frontend and backend development (intersection).
4. Find languages that are primarily frontend but not backend (difference).
5. Check if `{"HTML", "CSS"}` is a subset of `frontend_langs`.

In [14]:
frontend_langs = {"HTML", "CSS", "JavaScript", "Python"}
backend_langs = {"Python", "Java", "C#", "SQL"}
unique_langs=frontend_langs.union(backend_langs)
print(unique_langs)

{'HTML', 'C#', 'JavaScript', 'Java', 'SQL', 'Python', 'CSS'}


In [15]:
common_langs=frontend_langs.intersection(backend_langs)
common_langs

{'Python'}

In [17]:
difference_langs=frontend_langs.difference(backend_langs)
difference_langs

{'CSS', 'HTML', 'JavaScript'}

In [18]:
frontend_langs = {"HTML", "CSS", "JavaScript", "Python"}
is_subset={"HTML", "CSS"}
print(is_subset.issubset(frontend_langs))

True



1. **Problem 1: Set Creation & Uniqueness:**Create a list called `sensor_readings = [22.5, 23.0, 22.5, 24.1, 23.0, 25.0]`.
Convert `sensor_readings` to a set named `unique_readings` to find all distinct temperature values. Print `unique_readings` and its length.
Attempt to add `24.1` to `unique_readings` and then `26.0`. 
Print the set after each operation.

## Tuple Practice Problem

1. Create a tuple named `book_details` with the following information: "The Hitchhiker's Guide to the Galaxy",
"Douglas Adams", 1979, "Science Fiction". Print the tuple.
2. Print the title of the book and the publication year from `book_details` using indexing.
3. Create a single-element tuple containing only the string "Solo". Print it and its type to verify it's a tuple.

In [19]:
book_details=("The Hitchhiker's Guide to the Galaxy","Douglas Adams", 1979, "Science Fiction")
print(book_details)

("The Hitchhiker's Guide to the Galaxy", 'Douglas Adams', 1979, 'Science Fiction')


In [20]:
book_details[0]


"The Hitchhiker's Guide to the Galaxy"

In [21]:
book_details[2]

1979

In [22]:
single_ele_tup=("hello")
print(single_ele_tup,type(single_ele_tup))

hello <class 'str'>


In [23]:
single_ele_tup=("hello",)
print(single_ele_tup,type(single_ele_tup))

('hello',) <class 'tuple'>


In [25]:
single_ele_tup=(2,)
print(single_ele_tup,type(single_ele_tup))

(2,) <class 'tuple'>


1. Given `rgb_color_code = (255, 0, 128)`. Try to change the green component to `50` (i.e., `rgb_color_code[1] = 50`).
What error do you get? Explain why.

In [27]:
rgb_color_code = (255, 0, 128)
rgb_color_code[1]=50

TypeError: 'tuple' object does not support item assignment

In [29]:
rgb_color_code = ([(255, 0, 128)],)
print(rgb_color_code[0].append(50))

None


In [41]:
rgb_color_code =( [255, 0, 128],)
print(rgb_color_code[0].append(50))

None


In [42]:
rgb_color_code 

([255, 0, 128, 50],)

In [43]:
try:
    rgb_color_code = (255, 0, 128)
    rgb_color_code[1]=50
except TypeError as e:
    print("TypeError:",e)

TypeError: 'tuple' object does not support item assignment


2. Create a tuple `complex_tuple = ([1, 2], "mutable", (3, 4))`. Try to append `3` to the inner list `[1, 2]` (i.e.,
`complex_tuple[0].append(3)`). Does this work? Explain why or why not, relating it to mutability.

In [39]:
complex_tuple = ([1, 2], "mutable", (3, 4))
complex_tuple[0].append(3)
complex_tuple

([1, 2, 3], 'mutable', (3, 4))

1. You have a tuple of daily temperatures: `temperatures = (25, 27, 25, 29, 28, 27, 30)`.
2. Count how many times `27` appears in the `temperatures` tuple.
3. Find the index of the first occurrence of `25`.
4. Find the length of the `temperatures` tuple.
5. Extract a slice containing temperatures from the 3rd day to the 5th day (inclusive) using forward slicing.
6. Extract the last two temperatures using backward slicing.

In [44]:
temperatures = (25, 27, 25, 29, 28, 27, 30)
count=temperatures.count(27)
print(count)

2


In [45]:
temperatures.index(25)

0

In [46]:
len(temperatures)

7

In [47]:
temperatures[2:5]

(25, 29, 28)

In [48]:
temperatures[-1:-3:-1]

(30, 27)

## Dictionary Practice Problem

1. Create a dictionary called `employee_info` with keys for `name`, `employee_id`, `department`, and `salary`. Populate
it with sample data. Print the entire dictionary.
2. Print the employee's `department` using key access.
3. Attempt to access a non-existent key, `phone_number`, using direct access (`employee_info['phone_number']`).
What error occurs?
4. Access `phone_number` again, but this time use `get()` with a default value of "Not Available". Print the result.

In [49]:
employee_info={
    "name":"vipul",
    "employee_id":"vip546",
    "department":"Tech solution",
    "salary":27000
}
print(employee_info)

{'name': 'vipul', 'employee_id': 'vip546', 'department': 'Tech solution', 'salary': 27000}


In [50]:
employee_info["department"]

'Tech solution'

In [51]:
employee_info["phone_number"]

KeyError: 'phone_number'

In [52]:
try:
    employee_info["phone_number"]
except KeyError as e:
    print("KeyError:",e)

KeyError: 'phone_number'


In [55]:
employee_info.get("phone_number","not available")

'not available'

Given `inventory = {"apples": 50, "bananas": 30, "oranges": 20}`.
2. Print a list of all item names (keys).
3. Print a list of all quantities (values).
4. Print a list of all `(item, quantity)` pairs.
5. Update the inventory: increase "apples" to 60 and add "grapes" with a quantity of 40. Print the updated inventory.
6. Remove "bananas" from the inventory and print its quantity that was removed. Print the final inventory.

In [56]:
inventory = {"apples": 50, "bananas": 30, "oranges": 20}
inventory.keys()

dict_keys(['apples', 'bananas', 'oranges'])

In [57]:
inventory.values()

dict_values([50, 30, 20])

In [58]:
inventory.items()

dict_items([('apples', 50), ('bananas', 30), ('oranges', 20)])

In [59]:
inventory.update(apples=60,grapes=40)
inventory

{'apples': 60, 'bananas': 30, 'oranges': 20, 'grapes': 40}

In [62]:
inventory.pop("bananas")

30

In [63]:
inventory

{'apples': 60, 'oranges': 20, 'grapes': 40}

 `1. Given a list of product prices: `product_prices = [("laptop", 1200), ("keyboard", 75), ("mouse", 25)]`. Use dictionary
comprehension to create a dictionary where product names are keys and prices are values.`


In [65]:
product_prices = [("laptop", 1200), ("keyboard", 75), ("mouse", 25)]
my_dict={product_name:product_name for product_name in product_prices}
my_dict

{('laptop', 1200): ('laptop', 1200),
 ('keyboard', 75): ('keyboard', 75),
 ('mouse', 25): ('mouse', 25)}

In [3]:
product_prices = [("laptop", 1200), ("keyboard", 75), ("mouse", 25)]
my_dict={key:value for(key,value) in product_prices}
my_dict

{'laptop': 1200, 'keyboard': 75, 'mouse': 25}

In [4]:
type(my_dict)

dict

2. Given a dictionary of item quantities: `items_quantities = {"pen": 10, "notebook": 5, "eraser": 0, "pencil": 12}`. Use
dictionary comprehension to create a new dictionary `in_stock_items` containing only items with a quantity greater
than 0.

In [6]:
items_quantities = {"pen": 10, "notebook": 5, "eraser": 0, "pencil": 12}
in_stock_items={key:value for(key,value) in items_quantities.items() if value>0}
in_stock_items

{'pen': 10, 'notebook': 5, 'pencil': 12}

3. From `items_quantities`, create `price_per_item`` where the key is the item name and the value is a
hypothetical price (e.g., item quantity * 2).

In [7]:
items_quantities = {"pen": 10, "notebook": 5, "eraser": 0, "pencil": 12}
price_per_item ={key:(value*2) for(key,value) in items_quantities.items()}
price_per_item 

{'pen': 20, 'notebook': 10, 'eraser': 0, 'pencil': 24}

1.Create a dictionary where keys are numbers from 1 to 5 and values are their squares using dictionary comprehension.

2.Convert a list to a dictionary where each element becomes a key and the value is its length:
Example list: ["apple", "banana", "cherry"]

3.Flip a dictionary using dictionary comprehension:
Input: {'a': 1, 'b': 2, 'c': 3}
Output: {1: 'a', 2: 'b', 3: 'c'}

In [11]:
dict_num={key:(key**2) for key in range(5)}
dict_num

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [15]:
fruits=["apple", "banana", "cherry"]
new_dict={key:len(key) for key in fruits}
new_dict

{'apple': 5, 'banana': 6, 'cherry': 6}

In [24]:
input= {'a': 1, 'b': 2, 'c': 3}
type(Input)
output={value:key for(key,value) in input.items()}
output

{1: 'a', 2: 'b', 3: 'c'}

1.Filter dictionary items: From a dictionary of numbers and their squares (1 to 10), 
create a new dictionary that only includes items where the value (square) is greater than 30.

2.Use two lists to create a dictionary:
Example: keys = ['name', 'age', 'city'], values = ['John', 25, 'New York']

3.Count frequency of each character in a string using dictionary comprehension.
Example input: "hello"



In [25]:
dict_square={key:(key**2) for key in range(10)}
dict_square

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [26]:
new_dict_sq={key:value for(key,value) in dict_square.items() if value>30}
new_dict_sq

{6: 36, 7: 49, 8: 64, 9: 81}

In [31]:
keys = ['name', 'age', 'city']
values = ['John', 25, 'New York']
dict_key_val={key:value for key in keys for value in values}
dict_key_val

{'name': 'New York', 'age': 'New York', 'city': 'New York'}

In [33]:
keys = ['name', 'age', 'city']
values = ['John', 25, 'New York']
dict_key_val={key:value for key,value in zip(keys,values)}
dict_key_val

{'name': 'John', 'age': 25, 'city': 'New York'}

In [34]:
keys = ['name', 'age', 'city','office']
values = ['John', 25, 'New York']
dict_key_val={key:value for key,value in zip(keys,values)}
dict_key_val

{'name': 'John', 'age': 25, 'city': 'New York'}

In [35]:
keys = ['name', 'age', 'city']
values = ['John', 25, 'New York',"India"]
dict_key_val={key:value for key,value in zip(keys,values)}
dict_key_val

{'name': 'John', 'age': 25, 'city': 'New York'}

In [38]:
str_val="hello"
str_dict={key:len(key) for key in str_val }
str_dict

{'h': 1, 'e': 1, 'l': 1, 'o': 1}

In [50]:
str_val="hello"
str_dict={key:str_val.count(key) for key in str_val }
str_dict

{'h': 1, 'e': 1, 'l': 2, 'o': 1}

In [51]:
str_val="welcome to the programming world of python ! we are here now"
str_dict={key:str_val.count(key) for key in str_val }
str_dict

{'w': 4,
 'e': 7,
 'l': 2,
 'c': 1,
 'o': 7,
 'm': 3,
 ' ': 11,
 't': 3,
 'h': 3,
 'p': 2,
 'r': 5,
 'g': 2,
 'a': 2,
 'i': 1,
 'n': 3,
 'd': 1,
 'f': 1,
 'y': 1,
 '!': 1}

1.Nested dictionary comprehension: Create a multiplication table (1 to 5) as a nested dictionary.
Example: table[2][3] = 6

2.Given a list of tuples:
data = [("math", 95), ("science", 89), ("english", 92)]
Create a dictionary where subject is the key and score is the value, but only include subjects with score > 90.

3.Reverse and filter a dictionary:
Input: {'a': 3, 'b': 7, 'c': 1, 'd': 9}
Output: {3: 'a', 7: 'b', 9: 'd'} (only values > 2

In [ ]:
multiplication_table={key:{number:

In [52]:
data = [("math", 95), ("science", 89), ("english", 92)]
dict_data={key:value for(key,value) in data}
dict_data

{'math': 95, 'science': 89, 'english': 92}

In [53]:
data = [("math", 95), ("science", 89), ("english", 92)]
dict_data={key:value for(key,value) in data if value>90}
dict_data

{'math': 95, 'english': 92}

In [55]:
input = {'a': 3, 'b': 7, 'c': 1, 'd': 9}
output={key:value for(value,key) in input.items() if key>2}
output

{3: 'a', 7: 'b', 9: 'd'}

# Practice--28-07-2025
1.iterations
2.tuple to dict comprehension ----- dict to tuple
3.value iteration
4.packing and unpacking

In [1]:
input= {'a': 1, 'b': 2, 'c': 3}
for key in input:
    print(key)
    

a
b
c


In [2]:
for value in input:
    print(value)

a
b
c


In [3]:
for key in input.keys():
    print(key)

a
b
c


In [4]:
for value in input.values():
    print(value)

1
2
3


In [28]:
input= {'a': 1, 'b': 2, 'c': 3}
output={}
for i in input.keys():
    output[i]=input[i]
    print(output[i])

1
2
3


In [38]:
input= {'a': 1, 'b': 2, 'c': 3}
output={}
for i in input.keys():
    j=i
    print(j)

a
b
c


In [40]:
input= {'a': 1, 'b': 2, 'c': 3}
output={}
for i in input.keys():
    output[i]=input[i]
    print(output[i])

1
2
3


In [41]:
output.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [45]:
output={}
for key,value in input.items():
    output[value]=key
print(output)

{1: 'a', 2: 'b', 3: 'c', 'a': 1, 'b': 2, 'c': 3}


In [47]:
#data = [("math", 95), ("science", 89), ("english", 92)]
#dict_data={key:value for(key,value) in data}
#dict_data
data = [("math", 95), ("science", 89), ("english", 92)]
dict_data={}
for key,value in data:
    dict_data[key]=value
print(dict_data)

{'math': 95, 'science': 89, 'english': 92}


In [49]:
tup_a=(
    ("math", 95), ("science", 89), ("english", 92)
)
dict_tup={key:value for(key,value) in tup_a}
dict_tup

{'math': 95, 'science': 89, 'english': 92}

In [55]:
tup_b=([],)
dict_tup_b={'math': 95, 'science': 89, 'english': 92}
for key,value in dict_tup_b.items():
    tup_b[0].append(zip(key,value))
print(tup_b)
    


TypeError: 'int' object is not iterable

In [56]:
tup_b=([],)
dict_tup_b={'math': 95, 'science': 89, 'english': 92}
for key,value in dict_tup_b.items():
    tup_b[0].append((key,value))
print(tup_b)

([('math', 95), ('science', 89), ('english', 92)],)


In [57]:
type(tup_b)

tuple

In [58]:
list_a=[]
dict_tup_c={'math': 95, 'science': 89, 'english': 92}
for key,value in dict_tup_c.items():
    list_a.append(key,value)
    print(list_a)



TypeError: list.append() takes exactly one argument (2 given)

In [59]:
list_a=[]
dict_tup_c={'math': 95, 'science': 89, 'english': 92}
for key,value in dict_tup_c.items():
    list_a.append((key,value))
print(list_a)

[('math', 95), ('science', 89), ('english', 92)]


In [60]:
output={}
for key,valu in list_a:
    output[key]=value
print(output)

{'math': 92, 'science': 92, 'english': 92}


In [62]:
dict_set_a={'math': 95, 'science': 89, 'english': 92}
set_a=set()
for key,value in dict_set_a.items():
    set_a.add((key,valu))
print(set_a)

{('math', 92), ('science', 92), ('english', 92)}


In [64]:
tup_b=(('math', 95), ('science', 89), ('english', 92))
output_as_dict={}
for key,value in tup_b:
    output_as_dict[key]=value
print(output_as_dict)

                


{'math': 95, 'science': 89, 'english': 92}


# packing and unpacking in list

In [65]:
list_a=[1,2,3,3,4]
a,b,c,d,e=list_a
print(a,b,c,d,e)

1 2 3 3 4


In [66]:
list_a=[1,2,3,3,4]
a,b,c,d=list_a
print(a,b,c,d)

ValueError: too many values to unpack (expected 4)

In [67]:
list_a=[1,2,3,3,4]
a,b,c,d,e,f=list_a
print(a,b,c,d,e,f)

ValueError: not enough values to unpack (expected 6, got 5)

In [70]:
list_a=[1,2,3,3,4]
*a=list_a
print(a)

SyntaxError: starred assignment target must be in a list or tuple (3326947914.py, line 2)

In [71]:
list_a=[1,2,3,3,4]
*a,b=list_a
print(a,b)

[1, 2, 3, 3] 4


In [72]:
list_a=[1,2,3,3,4]
a,b,*c,d=list_a
print(a,b,c,d)

1 2 [3, 3] 4


In [74]:
list_a=[1,2,3,3,4]
a,*b,*c,d=list_a
print(a,b,c,d)

SyntaxError: multiple starred expressions in assignment (3525080019.py, line 2)

In [75]:
list_a=[1,2,3,3,4]
a,*b,*c=list_a
print(a,b,c)

SyntaxError: multiple starred expressions in assignment (3736421742.py, line 2)

In [76]:
a=[1,2,3]
b=[4,5,6]
print(*a,*b)

1 2 3 4 5 6


In [78]:
a=[1,2,3]
b=[4,5,6]
c=*a , *b
print(c)

(1, 2, 3, 4, 5, 6)


In [79]:
type(c)

tuple

In [111]:
a=[1,2,3]
b=[4,5,6]
d=*a,b
print(d)

(1, 2, 3, [4, 5, 6])


In [114]:
a=[1,2,3]
b=[4,5,6]
d=b,*a
print(d)

([4, 5, 6], 1, 2, 3)


In [112]:
type(c)

tuple

In [91]:
a=[1,2,3]
b=[4,5,6]
print(*a)

1 2 3


In [110]:
type(a)

int

In [96]:
d=[[1,2,3],
[4,5,6],(9,8,7)
  ]
a,*b,c=d
print(a[0],*b,c)

1 [4, 5, 6] (9, 8, 7)


In [98]:
tup_a=(1,2,3,"a","y")
a,b,c,d,e=tup_a
print(a,b,c,d,e)

1 2 3 a y


In [99]:
tup_a=(1,2,3,"a","y")
a,b,c,d,e,f=tup_a
print(a,b,c,d,e,f)

ValueError: not enough values to unpack (expected 6, got 5)

In [100]:
tup_a=(1,2,3,"a","y")
a,b,c,d=tup_a
print(a,b,c,d)

ValueError: too many values to unpack (expected 4)

In [103]:
tup_a=(1,2,3,"a","y")
a,*b=tup_a
print(a,b)



1 [2, 3, 'a', 'y']


In [104]:
type(a)

int

In [126]:
tup_a=(1,2,3,"a","y")
tup_b=("talib","ansari","coding")
c=tup_a,tup_b
print(c)


((1, 2, 3, 'a', 'y'), ('talib', 'ansari', 'coding'))


In [127]:
tup_a=(1,2,3,"a","y")
tup_b=("talib","ansari","coding")
#c=tup_a,*tup_b
tup_c=*tup_a,tup_b
print(tup_c)


(1, 2, 3, 'a', 'y', ('talib', 'ansari', 'coding'))


In [128]:
type(tup_c)

tuple

In [129]:
set_a={1,2,3,4,4,"a","b","c"}
a,b,c,d,e,f,g=set_a
print(a,b,c,d,e,f,g)

b 1 2 3 4 a c


In [130]:
a,*b=set_a
print(a,*b)

b 1 2 3 4 a c


In [131]:
set_a={1,2,3,4,4,"a","b","c"}
set_b={"talib","having","fun"}
set_c=*set_a,set_b
print(set_c)

('b', 1, 2, 3, 4, 'a', 'c', {'talib', 'having', 'fun'})


In [132]:
type(set_c)

tuple

In [133]:
set_a={1,2,3,4,4,"a","b","c"}
set_b={"talib","having","fun"}
set_c=set_a,set_b
print(set_c)

({'b', 1, 2, 3, 4, 'a', 'c'}, {'talib', 'having', 'fun'})


In [134]:
type(set_c)

tuple

In [135]:
person = {
    "name": "Pavan",
    "age": 30,
    "job": "Engineer"
}
a,b,c=person
print(a,b,c)

name age job


In [136]:
a,b,c=person.keys()
print(a,b,c)

name age job


In [137]:
a,b,c=person.values()
print(a,b,c)

Pavan 30 Engineer


In [138]:
a,b,c=person.items()
print(a,b,c)

('name', 'Pavan') ('age', 30) ('job', 'Engineer')


In [140]:
tup_d=(('name', 'Pavan'), ('age', 30),('job', 'Engineer'))
dict_d={}
for key,value in tup_d:
    dict_d[key]=value
print(dict_d)

{'name': 'Pavan', 'age': 30, 'job': 'Engineer'}


In [141]:
tup_d=(('name', 'Pavan'), ('age', 30),('job', 'Engineer'))
dict_d={}
for key,value in tup_d:
    dict_d[value]=key
print(dict_d)

{'Pavan': 'name', 30: 'age', 'Engineer': 'job'}


In [142]:
tup_e=(('name', 'Pavan'), ('age', 30),('job', 'Engineer'))
dict_e={key:value for key,value in tup_e}
print(dict_e)

{'name': 'Pavan', 'age': 30, 'job': 'Engineer'}


In [143]:
tup_e=(('name', 'Pavan'), ('age', 30),('job', 'Engineer'))
dict_e={key:value for value,key in tup_e}
print(dict_e)

{'Pavan': 'name', 30: 'age', 'Engineer': 'job'}


In [145]:
person = {
    "name": "Pavan",
    "age": 30,
    "job": "Engineer"
}
male={
    "height":5.7,
    "color":"black"
}
man=person
print(man)


{'name': 'Pavan', 'age': 30, 'job': 'Engineer'}


In [146]:
person = {
    "name": "Pavan",
    "age": 30,
    "job": "Engineer"
}
male={
    "height":5.7,
    "color":"black"
}
man=person,male
print(man)

({'name': 'Pavan', 'age': 30, 'job': 'Engineer'}, {'height': 5.7, 'color': 'black'})


In [148]:
person = {
    "name": "Pavan",
    "age": 30,
    "job": "Engineer"
}
male={
    "height":5.7,
    "color":"black"
}
man=*person,*male
print(man)

('name', 'age', 'job', 'height', 'color')


In [ ]:
person = {
    "name": "Pavan",
    "age": 30,
    "job": "Engineer"
}
male={
    "height":5.7,
    "color":"black"
}
man=person,*male
print(man)

In [150]:
my_fruits = ["apple", "banana", "cherry"]
print("\nFruits with their indices:")
for index in range(len(my_fruits)):
    print(f"Index {index}: {my_fruits[index]}")


Fruits with their indices:
Index 0: apple
Index 1: banana
Index 2: cherry


# Range

1. Print all numbers from 1 to 10 (inclusive) using `range()` and a `for` loop.



In [155]:
for i in range(1,11,):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [154]:
for i in range(10):
    print(i+1,end=" ")

1 2 3 4 5 6 7 8 9 10 

2. Generate and print a list of odd numbers from 1 to 20 (inclusive) using `range()` and then converting it to a list.

In [165]:
for i in range(0,20,2):
    print(i,end=" ")

0 2 4 6 8 10 12 14 16 18 

In [166]:
list_a=[]
for i in range(1,20):
    if i%2==0:
        list_a.append(i)
    else:
        continue
print(list_a)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [167]:
list_b=[x for x in range(20) if x%2==0]
print(list_b)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


3. Print numbers from 10 down to 1 using `range()` and a `for` loop.

In [170]:
for i in range(10,0,-1):
    print(i,end=" ")

10 9 8 7 6 5 4 3 2 1 

In [171]:
list_c=[]
for i in range(10,0,-1):
    list_c.append(i)
print(list_c)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [172]:
list_d=[x for x in range(10,0,-1)]
print(list_d)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


1. Given `students = ["Alice", "Bob", "Charlie", "David"]`. Print each student's name, along with their index (e.g.,
"Student 0: Alice") using a `for` loop and `range(len())`.

In [175]:
students = ["Alice", "Bob", "Charlie", "David"]
for index in range(len(students)):
    print(f"student {index}:{students[index]}")

student 0:Alice
student 1:Bob
student 2:Charlie
student 3:David


2. Given `product_prices = {"laptop": 1200, "keyboard": 75, "mouse": 25}`. Iterate through the dictionary and print each
product name and its price in the format: "Product: [Name], Price: $[Price]".

In [177]:
product_prices = {"laptop": 1200, "keyboard": 75, "mouse": 25}
for key,value in product_prices.items():
    print(f"product :{key} ,  price:{value}")

product :laptop ,  price:1200
product :keyboard ,  price:75
product :mouse ,  price:25


3. Calculate the total price of all products in `product_prices` using a `for` loop.

In [179]:
total_price=0
product_prices = {"laptop": 1200, "keyboard": 75, "mouse": 25}
for value in product_prices.values():
    total_price+=value
print(total_price)

1300


1. Create a list `temperatures = [22, 25, 19, 28, 23, 30]`. Use a `for` loop with `range(len())` to modify this list in-place: if
a temperature is below 20, change it to 20. Print the modified list.

In [181]:
temperatures = [22, 25, 19, 28, 23, 30]
for i in range(len(temperatures)):
    if temperatures[i]<20:
        temperatures[i]=20
    print(temperatures[i],end=" ")

22 25 20 28 23 30 

2. Generate a dictionary where keys are numbers from 1 to 5 and values are their cubes, using dictionary
comprehension and `range()`. Print the dictionary.

In [183]:
dict_cubes={key:key**3 for key in range(1,5)}
dict_cubes

{1: 1, 2: 8, 3: 27, 4: 64}

3. You have two lists: `names = ["Alice", "Bob", "Charlie"]` and `scores = [85, 92, 78]`. Use a `for` loop with `range(len())`
to combine these into a list of tuples, where each tuple is `(name, score)`. Print the resulting list.

In [193]:
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
list_a=[]
for i in range(len(names)):
    for j in range(len(scores)):
        list_a.append((names[i],scores[j]))
print(list_a)

[('Alice', 85), ('Alice', 92), ('Alice', 78), ('Bob', 85), ('Bob', 92), ('Bob', 78), ('Charlie', 85), ('Charlie', 92), ('Charlie', 78)]


In [194]:
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
list_a=[]
for i in range(len(names)) for j in range(len(scores)):
    list_a.append((names[i],scores[j]))
print(list_a)

SyntaxError: invalid syntax (1508769496.py, line 4)

In [202]:
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
paired=zip(names,scores)
print(list(paired))

[('Alice', 85), ('Bob', 92), ('Charlie', 78)]


In [203]:
list_pair=[]
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
paired=zip(names,scores)
#print(list(paired))
for i in range(len(paired)):
    list_pair.append(paired(i))
print(list_pair)
    

TypeError: object of type 'zip' has no len()

In [206]:
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
res_list=[]
for i in range(len(names)):
    res_list.append((names[i],scores[i]))
print(res_list)

[('Alice', 85), ('Bob', 92), ('Charlie', 78)]
